export const SHEET_NAMES = {
  DL_DOANH_THU_APP: 'DL_DOANH_THU_APP',
  DL_DOANH_THU_CUA_HANG: 'DL_DOANH_THU_CUA_HANG',
  DL_SO_QUY: 'DL_SO_QUY',
  DL_TON_KHO: 'DL_TON_KHO',
  DL_THAT_THOAT_NVL: 'DL_THAT_THOAT_NVL',
  DL_CONG_NO: 'DL_CONG_NO',
  DL_THU_MUA: 'DL_THU_MUA',

  CEO_DASHBOARD: 'CEO_DASHBOARD',
  PL_TUAN: 'P&L_TUAN',
  DONG_TIEN_TUAN: 'DONG_TIEN_TUAN',
  CAN_DOI_RUT_GON: 'CAN_DOI_RUT_GON',
  DU_TOAN_TUAN_TOI: 'DU_TOAN_TUAN_TOI',
  THAT_THOAT_CHI_TIET: 'THAT_THOAT_CHI_TIET',
  BAN_LAM_VIEC_KE_TOAN: 'BAN_LAM_VIEC_KE_TOAN',

  IMPORT_LICH_SU: 'IMPORT_LICH_SU',
  IMPORT_DONG_LOI: 'IMPORT_DONG_LOI',
  IMPORT_DU_LIEU_TRUNG: 'IMPORT_DU_LIEU_TRUNG',
  IMPORT_DU_LIEU_LECH: 'IMPORT_DU_LIEU_LECH',
  AUDIT_LOG: 'AUDIT_LOG',
  CAI_DAT_BOT: 'CAI_DAT_BOT',
  CAI_DAT_NGUONG: 'CAI_DAT_NGUONG',

  // Backward-compatible aliases for older code paths. They intentionally map to
  // the V5 Data Master sheet names so production does not write to missing tabs.
  IMPORT_NHAT_KY_XU_LY: 'AUDIT_LOG',
  CAI_DAT_NGUONG_CANH_BAO: 'CAI_DAT_NGUONG',
  CAI_DAT_BOT_BAO_CAO: 'CAI_DAT_BOT'
} as const;

export type SheetName = (typeof SHEET_NAMES)[keyof typeof SHEET_NAMES];
